application: todos-rest-server
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /test
  static_dir: test

- url: /.*
  script: main.py
